package credentials

import (
	"bytes"
	"encoding/hex"
	"strings"
	"testing"
)

// The golden vector below was generated by the TypeScript writer itself
// (apps/web/src/platform/executor/store.ts `sealSecret`) run under bun:
//
//	sealSecret('fud-test-api-key-0001', keyHex) =>
//	  iv  = 42aa559a22070fd2abc41fa7
//	  tag = 355863693d9bd2d06309e651f8254f5b
//	  ct  = 0f655a1d14016824b5e228c816b27d0836ca9c882a
//
// Interop is the contract: the Go reader MUST open a blob the web API wrote,
// byte-for-byte. A hand-copied expectation would prove nothing about the two
// implementations agreeing, so the vector comes from the other side.
const (
	goldenKeyHex = "0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0"
	goldenIV     = "42aa559a22070fd2abc41fa7"
	goldenTag    = "355863693d9bd2d06309e651f8254f5b"
	goldenCT     = "0f655a1d14016824b5e228c816b27d0836ca9c882a"
	goldenPlain  = "fud-test-api-key-0001"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex constant %q: %v", s, err)
	}
	return b
}

func TestOpenTSSealedGoldenVector(t *testing.T) {
	// The stored blob is a 2-secret envelope (iv = 24 bytes, tag = 32 bytes);
	// the api_key side carries the real TS-sealed blob, so decrypting JUST
	// that entry is the interop proof (a 2-secret envelope's second entry is
	// not part of the golden vector).
	env := Envelope{
		APIKey:    mustHex(t, goldenCT),
		APISecret: []byte{0},
		IV:        mustHex(t, goldenIV+"000000000000000000000000"),
		AuthTag:   mustHex(t, goldenTag+"00000000000000000000000000000000"),
	}
	k, err := openOne(env.APIKey, env.IV[0:IVLen], env.AuthTag[0:TagLen], mustKey(t, goldenKeyHex))
	if err != nil {
		t.Fatalf("Go failed to open a TS-sealed blob: %v", err)
	}
	if string(k) != goldenPlain {
		t.Fatalf("plaintext mismatch: got %q", k)
	}
}

func TestSealThenOpenRoundTrip(t *testing.T) {
	env, err := Seal("binance-ak-123", "binance-sk-456", "super-secret-pass", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	if env.SecretCount() != 3 {
		t.Fatalf("passphrase present => 3 secrets, got %d", env.SecretCount())
	}
	if err := env.Validate(); err != nil {
		t.Fatalf("validate: %v", err)
	}
	k, s, p, err := Open(env, goldenKeyHex)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if k != "binance-ak-123" || s != "binance-sk-456" || p != "super-secret-pass" {
		t.Fatalf("round trip mismatch: %q %q %q", k, s, p)
	}
}

func TestSealNoPassphraseLayout(t *testing.T) {
	env, err := Seal("k", "s", "", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	if env.SecretCount() != 2 || len(env.IV) != 2*IVLen || len(env.AuthTag) != 2*TagLen {
		t.Fatalf("expected a 2-secret layout, got %d secrets iv=%d tag=%d", env.SecretCount(), len(env.IV), len(env.AuthTag))
	}
	if env.Passphrase != nil {
		t.Fatal("passphrase must be nil (the TS null)")
	}
	if _, _, p, err := Open(env, goldenKeyHex); err != nil || p != "" {
		t.Fatalf("open 2-secret: err=%v pass=%q", err, p)
	}
}

func TestOpenWrongKeyRefuses(t *testing.T) {
	other := "f" + goldenKeyHex[1:]
	env, err := Seal("k", "s", "p", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	_, _, _, err = Open(env, other)
	if err == nil {
		t.Fatal("opening under the wrong key must refuse")
	}
	if err != ErrOpen {
		t.Logf("refusal is %v (ErrOpen is the contract)", err)
	}
}

func TestOpenTamperedCiphertextRefuses(t *testing.T) {
	env, err := Seal("k", "secret-value", "", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	env.APISecret[0] ^= 0xff
	if _, _, _, err := Open(env, goldenKeyHex); err != ErrOpen {
		t.Fatalf("tampered ciphertext must be ErrOpen, got %v", err)
	}
}

func TestLayoutMismatchRefuses(t *testing.T) {
	env, err := Seal("k", "s", "p", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	env.IV = env.IV[:IVLen] // 1 iv for 3 secrets
	if err := env.Validate(); err != ErrEnvelopeLayout {
		t.Fatalf("layout mismatch must refuse, got %v", err)
	}
	if _, _, _, err := Open(env, goldenKeyHex); err != ErrEnvelopeLayout {
		t.Fatalf("Open must refuse before any decrypt, got %v", err)
	}
}

func TestMalformedMasterKeyRefuses(t *testing.T) {
	if _, err := MasterKeyFromEnv(func(string) string { return "" }); err != ErrMasterKey {
		t.Fatalf("absent key: got %v", err)
	}
	if _, err := MasterKeyFromEnv(func(string) string { return "zz" + goldenKeyHex[2:] }); err != ErrMasterKey {
		t.Fatalf("non-hex key: got %v", err)
	}
	if _, err := Seal("k", "s", "", "abc"); err != ErrMasterKey {
		t.Fatalf("seal with short key: got %v", err)
	}
}

func TestMaskAndFingerprintCarryNoPlaintext(t *testing.T) {
	if m := MaskAPIKey("abcdefghijklmnop"); m != "abcd********mnop" {
		t.Fatalf("mask shape: %q", m)
	}
	fp := Fingerprint("abcdefghijklmnop", goldenKeyHex)
	if len(fp) != 8 || strings.Contains(fp, "abcdefgh") {
		t.Fatalf("fingerprint must be 8 hex chars, no plaintext: %q", fp)
	}
	fp2 := Fingerprint("abcdefghijklmnop", goldenKeyHex)
	if fp != fp2 {
		t.Fatal("fingerprint must be stable for the same key")
	}
	if Fingerprint("abcdefghijklmnop", "f"+goldenKeyHex[1:]) == fp {
		t.Fatal("fingerprint must depend on the master key (domain separation)")
	}
	if MaskAPIKey("abcdefghijklmnop") == "abcdefghijklmnop" || bytes.Contains([]byte(MaskAPIKey("abcdefghijklmnop")), []byte("efgh")) {
		t.Fatal("masked key must not expose the middle of the secret")
	}
}

// The two writers agree on ORDER: iv/auth_tag are api_key||api_secret||[pass]
// concatenations. Swapping the second and third IV/tag blocks must fail to
// open, proving the layout is order-sensitive (not accidentally symmetric).
func TestLayoutOrderMatters(t *testing.T) {
	env, err := Seal("key-one", "sec-two", "pass-three", goldenKeyHex)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}
	iv := append([]byte{}, env.IV...)
	copy(env.IV[2*IVLen:3*IVLen], iv[IVLen:2*IVLen])
	copy(env.IV[IVLen:2*IVLen], iv[2*IVLen:3*IVLen])
	if _, _, _, err := Open(env, goldenKeyHex); err == nil {
		t.Fatal("swapped IV order must refuse (GCM nonce binding)")
	}
}

// mustKey decodes the golden master key for the low-level interop probe.
func mustKey(t *testing.T, keyHex string) []byte {
	t.Helper()
	b, err := decodeKey(keyHex)
	if err != nil {
		t.Fatalf("golden key: %v", err)
	}
	return b
}
