// Package credentials is the executor-side key custody boundary (objective
// §8.4: the executor uses a credential_id, never plaintext spread through the
// system). It is the Go port of the envelope crypto the web API writes with
// (apps/web/src/platform/executor/store.ts `sealSecret`/`openSecret`,
// PRD §44): AES-256-GCM, one 12-byte IV and 16-byte tag PER secret, all
// ciphertexts concatenated in column order (api_key, api_secret,
// [passphrase]) in executor.exchange_accounts (iv and auth_tag are the
// concatenations in the same order — see database/schema/executor-schema.sql).
//
// The formats are byte-identical by construction and proven in
// credentials_test.go against a golden vector generated by the TS
// `sealSecret` itself: a row the web API seals MUST unseal here and vice
// versa, or the two writers/readers would silently fork the credential set.
//
// # PLAINTEXT HANDLING
//
// Plaintext secrets never leave this package: no exported value, helper or
// error message contains a secret (only ever the masked key,
// MaskAPIKey). Unseal failure refuses loudly naming the credential, the
// audience of an unseal call is the exchange adapter it is handed to.
package credentials

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// IVLen is the GCM nonce length: 12 bytes, the standard size and exactly the
// length store.ts allocates per secret (`randomBytes(12)`).
const IVLen = 12

// TagLen is the GCM authentication tag length: 16 bytes (the standard tag).
const TagLen = 16

var masterKeyRE = regexp.MustCompile(`^[0-9a-fA-F]{64}$`)

var (
	// ErrMasterKey malformed/absent — credential operations are fail-closed
	// (parity with store.ts masterKeyFromEnv's verbatim-shaped refusal).
	ErrMasterKey = errors.New("FUDCOURT_EXECUTOR_MASTER_KEY missing or malformed (64 hex chars = 32 bytes required) — credential operations are fail-closed")

	// ErrEnvelopeLayout: the stored concatenation does not match the secret
	// count (parity with store.ts's "credential envelope layout does not
	// match the stored secret count").
	ErrEnvelopeLayout = errors.New("credential envelope layout does not match the stored secret count")

	// ErrOpen: GCM verification failed — wrong key or tampered ciphertext.
	// Never carries the plaintext or the ciphertext.
	ErrOpen = errors.New("credential envelope failed to open (wrong key or tampered ciphertext)")
)

// MasterKeyFromEnv reads and validates the master key from an env lookup.
// Absent or malformed => ErrMasterKey: a credential operation must stop
// loudly, never fall back to a fabricated key.
func MasterKeyFromEnv(getenv func(string) string) (string, error) {
	raw := getenv("FUDCOURT_EXECUTOR_MASTER_KEY")
	if !masterKeyRE.MatchString(raw) {
		return "", ErrMasterKey
	}
	return raw, nil
}

// MaskAPIKey renders the display-safe key (parity with the TS maskApiKey).
// The masked form is the only form allowed outside this package.
func MaskAPIKey(key string) string {
	if len(key) <= 8 {
		return strings.Repeat("*", len(key))
	}
	return key[:4] + strings.Repeat("*", len(key)-8) + key[len(key)-4:]
}

// Envelope is the stored credential envelope: one row of
// executor.exchange_accounts's sealed columns, Go-side.
type Envelope struct {
	APIKey    []byte
	APISecret []byte
	// Passphrase is nil when the exchange needs no passphrase (the TS null).
	Passphrase []byte
	IV         []byte
	AuthTag    []byte
}

// SecretCount is 3 when a passphrase is stored, 2 otherwise (the TS count).
func (e Envelope) SecretCount() int {
	if e.Passphrase == nil {
		return 2
	}
	return 3
}

// Validate checks the concatenated iv/auth_tag lengths match the secret count
// before any decrypt (parity with store.ts openCredentials' layout check).
func (e Envelope) Validate() error {
	n := e.SecretCount()
	if len(e.IV) != n*IVLen || len(e.AuthTag) != n*TagLen {
		return ErrEnvelopeLayout
	}
	return nil
}

// sealOne encrypts one plaintext under the key with a fresh 12-byte IV.
// A never-repeating GCM nonce is cryptographic necessity (a repeat under one
// key breaks GCM), so rand.Read failure is a hard refusal — never a fabricated
// nonce.
func sealOne(plain, key []byte) (iv, ct, tag []byte, err error) {
	gcm, err := newGCM(key)
	if err != nil {
		return nil, nil, nil, err
	}
	iv = make([]byte, IVLen)
	if _, err := rand.Read(iv); err != nil {
		return nil, nil, nil, fmt.Errorf("credential seal: iv source: %w", err)
	}
	sealed := gcm.Seal(nil, iv, plain, nil)
	return iv, sealed[:len(sealed)-TagLen], sealed[len(sealed)-TagLen:], nil
}

// openOne decrypts one secret. Failure returns ErrOpen — the GCM tag IS the
// wrong-key/tamper signal; no plaintext, ciphertext or key material is
// included in the error.
func openOne(ct []byte, iv, tag, key []byte) ([]byte, error) {
	gcm, err := newGCM(key)
	if err != nil {
		return nil, err
	}
	if len(iv) != IVLen || len(tag) != TagLen {
		return nil, ErrEnvelopeLayout
	}
	out, err := gcm.Open(nil, iv, append(append([]byte{}, ct...), tag...), nil)
	if err != nil {
		return nil, ErrOpen
	}
	return out, nil
}

func newGCM(key []byte) (cipher.AEAD, error) {
	if len(key) != 32 {
		return nil, ErrMasterKey
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// Seal builds the envelope for one credential set (parity with
// sealCredentials): secrets sealed independently, then concatenated in
// api_key, api_secret, [passphrase] order.
func Seal(apiKey, apiSecret, passphrase, keyHex string) (Envelope, error) {
	key, err := decodeKey(keyHex)
	if err != nil {
		return Envelope{}, err
	}
	keyIV, keyCT, keyTag, err := sealOne([]byte(apiKey), key)
	if err != nil {
		return Envelope{}, err
	}
	secIV, secCT, secTag, err := sealOne([]byte(apiSecret), key)
	if err != nil {
		return Envelope{}, err
	}
	env := Envelope{APIKey: keyCT, APISecret: secCT, IV: append(keyIV, secIV...), AuthTag: append(keyTag, secTag...)}
	if passphrase != "" {
		pIV, pCT, pTag, err := sealOne([]byte(passphrase), key)
		if err != nil {
			return Envelope{}, err
		}
		env.Passphrase = pCT
		env.IV = append(env.IV, pIV...)
		env.AuthTag = append(env.AuthTag, pTag...)
	}
	return env, nil
}

// Open reverses Seal (parity with openCredentials). The passphrase is the
// empty string when none is stored.
func Open(e Envelope, keyHex string) (apiKey, apiSecret, passphrase string, err error) {
	if err := e.Validate(); err != nil {
		return "", "", "", err
	}
	key, err := decodeKey(keyHex)
	if err != nil {
		return "", "", "", err
	}
	n := 2
	if e.Passphrase != nil {
		n = 3
	}
	k, err := openOne(e.APIKey, e.IV[0:IVLen], e.AuthTag[0:TagLen], key)
	if err != nil {
		return "", "", "", err
	}
	s, err := openOne(e.APISecret, e.IV[IVLen:2*IVLen], e.AuthTag[TagLen:2*TagLen], key)
	if err != nil {
		return "", "", "", err
	}
	if n == 3 {
		p, err := openOne(e.Passphrase, e.IV[2*IVLen:3*IVLen], e.AuthTag[2*TagLen:3*TagLen], key)
		if err != nil {
			return "", "", "", err
		}
		return string(k), string(s), string(p), nil
	}
	return string(k), string(s), "", nil
}

func decodeKey(keyHex string) ([]byte, error) {
	if !masterKeyRE.MatchString(keyHex) {
		return nil, ErrMasterKey
	}
	key, err := hex.DecodeString(keyHex)
	if err != nil || len(key) != 32 {
		return nil, ErrMasterKey
	}
	return key, nil
}

// Fingerprint is a stable, non-reversible label for an unmasked key: the
// first 8 hex chars of HMAC-SHA256(key). It lets an operator correlate a
// stored row with a credential_id WITHOUT logging the secret (the hash is
// one-way; the master key is the domain separator so a fingerprint cannot be
// tested against an online rainbow table of common keys).
func Fingerprint(apiKey, keyHex string) string {
	key, err := decodeKey(keyHex)
	if err != nil {
		return MaskAPIKey(apiKey)
	}
	mac := hmac.New(sha256.New, key)
	mac.Write([]byte(apiKey))
	return hex.EncodeToString(mac.Sum(nil))[:8]
}
