#!/usr/bin/env python3
"""Cross-implementation sync gate: Python oracle vs Rust `fudcourt-sync` (Phase 6).

Two implementations of the balance sync exist during the parallel run
(`frontend/web/scripts/tools/sync-live.py` and `backend/sync/src/**`). This gate
proves they produce the SAME `assets` rows from the SAME inputs — byte for
byte — which is what makes promoting the Rust binary over the Python twin safe.

WHAT IS COMPARED

1. The projection: the exact `assets` rows each side would have written
   (chain, asset, quantity, value_usd, share_pct, wallet), in the same order,
   plus `#NET_WORTH=`. Both sides print it between
   `#ASSETS-PROJECTION-BEGIN/END` markers; the byte diff is the verdict.
2. The request trace: every upstream key each side asked for
   (`rpc|…`, `prices|…`, `hl|…`). A side that asks for an input the other never
   saw is diverging even if its rows happen to match.
3. The no-write invariant: neither trace may contain a `db|` entry. In oracle
   mode the Turso write path is unreachable by construction; if it ever appears
   one side regressed.

The capture in `tests/oracle/fixtures/capture.json` was generated by
`fixtures/make-capture.py` (deterministic, offline). Upstream truth is NOT what
is being tested here; that stays the live harnesses' job.

Usage:
    python3 scripts/verify/verify-sync.py [--capture FILE] [--bin PATH]

Offline. Exit codes: 0 identical, 1 divergence, 2 setup error.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]  # .../fudcourt  (verify/ -> scripts/ -> root)
FIXTURE = REPO / "tests" / "oracle" / "fixtures" / "capture.json"
PY_ORACLE = REPO / "frontend" / "web" / "scripts" / "tools" / "sync-live.py"
RUST_BIN = REPO / "backend" / "sync" / "target" / "release" / "fudcourt-sync"

BEGIN = "#ASSETS-PROJECTION-BEGIN"
END = "#ASSETS-PROJECTION-END"

GREEN, RED, DIM, RESET = "\033[32m", "\033[31m", "\033[2m", "\033[0m"


def check(ok: bool, label: str, detail: str = "") -> bool:
    print(f"  [{GREEN + 'PASS' + RESET if ok else RED + 'FAIL' + RESET}] {label}"
          + (f"  {DIM}{detail}{RESET}" if detail else ""))
    return ok


def run(cmd: list[str], env: dict | None = None) -> tuple[int, str]:
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, cwd=REPO)
    return proc.returncode, proc.stdout + proc.stderr


def parse_projection(out: str) -> tuple[list[str], str]:
    """The projection lines between the markers plus the NET_WORTH line."""
    lines: list[str] = []
    net = ""
    inside = False
    for line in out.splitlines():
        if line == BEGIN:
            inside = True
            continue
        if line == END:
            break
        if not inside:
            continue
        if line.startswith("#NET_WORTH="):
            net = line.split("=", 1)[1]
        elif line.startswith("["):
            lines.append(line)
    return lines, net


def parse_trace(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [l for l in path.read_text().splitlines() if l.strip()]


def diff_bites(a: list[str], b: list[str], limit: int = 6) -> list[str]:
    """Human-readable first divergences."""
    out: list[str] = []
    for i in range(max(len(a), len(b))):
        x = a[i] if i < len(a) else "<missing>"
        y = b[i] if i < len(b) else "<missing>"
        if x != y:
            out.append(f"line {i + 1}:\n    python: {x}\n    rust:   {y}")
            if len(out) >= limit:
                break
    if not out and len(a) != len(b):
        out.append(f"row count: python={len(a)} rust={len(b)}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--capture", default=str(FIXTURE))
    ap.add_argument("--bin", default=str(RUST_BIN))
    args = ap.parse_args()

    capture = Path(args.capture)
    rust_bin = Path(args.bin)
    if not capture.exists():
        print(f"capture fixture missing: {capture}\n"
              f"generate it: python3 {REPO/'tests/oracle/fixtures/make-capture.py'}")
        return 2
    if not rust_bin.exists():
        print(f"rust binary missing: {rust_bin}\n"
              f"build it: cd backend/sync && cargo build --release")
        return 2

    rows = json.loads(capture.read_text())["responses"]
    print(f"sync cross-implementation gate -- {len(rows)} recorded upstream responses")

    tmp = Path(tempfile.mkdtemp(prefix="fudcourt-sync-oracle-"))
    py_trace, rust_trace = tmp / "py.trace", tmp / "rust.trace"
    env = dict(os.environ)
    # Oracle mode needs no credential on either side; make the ambient .env
    # unable to satisfy a live path so a code path that tried one fails loudly
    # here instead of silently hitting the network.
    env["ALCHEMY_KEY"] = "fixture-placeholder-not-a-real-key"
    env["TURSO_AUTH_TOKEN"] = "fixture-placeholder-not-a-real-token"

    ok = True

    # ---- 1. Python oracle replay ----
    rc, out = run(
        [sys.executable, str(PY_ORACLE),
         "--oracle-inputs", str(capture), "--oracle-trace", str(py_trace)], env)
    if not check(rc == 0, "python oracle replay exits 0", out.strip().splitlines()[-1] if out.strip() else ""):
        print(out[-2000:])
        return 1
    py_rows, py_net = parse_projection(out)
    ok &= check(bool(py_rows), "python projection printed", f"{len(py_rows)} rows, net worth {py_net}")

    # ---- 2. Rust binary replay ----
    rc, out = run([str(rust_bin), "--oracle-inputs", str(capture),
                   "--oracle-trace", str(rust_trace)], env)
    if not check(rc == 0, "rust replay exits 0", out.strip().splitlines()[-1] if out.strip() else ""):
        print(out[-2000:])
        return 1
    rust_rows, rust_net = parse_projection(out)
    ok &= check(bool(rust_rows), "rust projection printed", f"{len(rust_rows)} rows, net worth {rust_net}")

    # ---- 3. Byte-identical projections ----
    same = py_rows == rust_rows
    if same:
        ok &= check(True, "projections byte-identical",
                    f"{len(py_rows)} rows, NET_WORTH {py_net} == {rust_net}")
    else:
        ok &= check(False, "projections byte-identical", "; ".join(diff_bites(py_rows, rust_rows)))

    # ---- 3b. Pinned golden projection ------------------------------------
    # The two-sided check alone cannot catch a change BOTH sides make the
    # same way (or, worse, a capture that misses rows: both sides then error
    # identically). The golden file is the third witness: it was generated
    # from the complete capture and any drift — extra rows, missing rows,
    # different rounding — fails here with the exact line.
    golden = FIXTURE.with_name("expected-projection.txt")
    if not golden.exists():
        ok &= check(False, "golden projection present", f"missing {golden}")
    else:
        want = [l for l in golden.read_text().splitlines() if l.startswith("[")]
        got = [l for l in py_rows if l.startswith("[")]
        if want == got:
            ok &= check(True, "projection matches pinned golden", f"{len(got)} rows")
        else:
            ok &= check(False, "projection matches pinned golden",
                        "; ".join(diff_bites(want, got)))

    # ---- 4. Same request set ----
    py_keys, rust_keys = parse_trace(py_trace), parse_trace(rust_trace)
    ok &= check(py_keys == rust_keys, "request traces identical",
                f"{len(py_keys)} keys" if py_keys else
                f"python={len(py_keys)} rust={len(rust_keys)}")

    # ---- 5. No Turso write on either side ----
    writes = [k for k in py_keys + rust_keys if k.startswith("db|")]
    ok &= check(not writes, "no Turso write issued (trace has no db| entry)",
                f"{len(writes)} write keys" if writes else "")

    # ---- 6. The fixture actually exercises both implementations ----
    kinds = {"rpc": 0, "prices": 0, "hl": 0}
    for k in py_keys or rows:
        pre = k.split("|", 1)[0]
        if pre in kinds:
            kinds[pre] += 1
    ok &= check(kinds["rpc"] > 0 and kinds["prices"] > 0 and kinds["hl"] > 0,
                "capture spans all three upstream families", str(kinds))

    print(f"\ntraces kept for inspection: {tmp}")
    if ok:
        print(f"{GREEN}SYNC_ORACLE_OK{RESET} ({len(py_rows)} rows, {len(py_keys)} request keys)")
        return 0
    print(f"{RED}SYNC_ORACLE_FAILED{RESET}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
