#!/usr/bin/env node
// Dump / check the live Turso schema (R-1, PLAN SG-2.1).
//   node scripts/dump-schema.mjs          -> writes db/schema.sql
//   node scripts/dump-schema.mjs --check  -> exits 1 if live != committed (drift alarm)
// Root .env supplies TURSO_AUTH_TOKEN (same walk-up rule as sync-live.py).
// Never prints secret values.
import fs from 'node:fs';
import path from 'node:path';

const webroot = path.resolve(new URL('.', import.meta.url).pathname, '..');       // apps/web
const root = path.resolve(new URL('.', import.meta.url).pathname, '../../..');      // repo root (.env)
function loadEnv() {
  const p = path.join(root, '.env');
  if (!fs.existsSync(p)) return;
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].trim();
  }
}
loadEnv();

const { createClient } = await import('@libsql/client');
const client = createClient({
  url: 'libsql://fud-balance-anvxxr.aws-ap-northeast-1.turso.io',
  authToken: process.env.TURSO_AUTH_TOKEN || '',
});

const res = await client.execute(
  "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name",
);
const header = [
  '-- Turso schema dump — GENERATED by scripts/dump-schema.mjs (do not hand-edit).',
  '-- Regenerate: node scripts/dump-schema.mjs | drift check: node scripts/dump-schema.mjs --check',
  '',
].join('\n');
const body = res.rows.map((r) => `${r.sql};`).join('\n\n') + '\n';
const dump = header + body;

const out = path.join(webroot, 'db', 'schema.sql');
const check = process.argv.includes('--check');

if (check) {
  const committed = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (committed === dump) {
    console.log('SCHEMA_OK (live == db/schema.sql)');
    process.exit(0);
  }
  console.error('SCHEMA_DRIFT: live schema differs from db/schema.sql');
  const a = new Set(committed.split('\n'));
  const b = new Set(dump.split('\n'));
  for (const l of b) if (!a.has(l)) console.error('  + ' + l.slice(0, 160));
  for (const l of a) if (!b.has(l)) console.error('  - ' + l.slice(0, 160));
  process.exit(1);
} else {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, dump);
  console.log(`wrote ${out} (${res.rows.length} objects)`);
}
