-- Turso schema dump — GENERATED by scripts/dump-schema.mjs (do not hand-edit).
-- Regenerate: node scripts/dump-schema.mjs | drift check: node scripts/dump-schema.mjs --check
CREATE TABLE accounts (
      code TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      type TEXT NOT NULL,
      statement TEXT NOT NULL
    );

CREATE TABLE assets (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      chain TEXT NOT NULL,
      asset TEXT NOT NULL,
      quantity REAL,
      value_usd REAL,
      share_pct REAL,
      wallet TEXT,
      updated_at TEXT DEFAULT (datetime('now'))
    );

CREATE TABLE journal (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      date TEXT NOT NULL,
      entry_code TEXT NOT NULL,
      debit_account TEXT,
      credit_account TEXT,
      memo TEXT,
      amount REAL,
      status TEXT DEFAULT 'Posted',
      created_at TEXT DEFAULT (datetime('now'))
    );

CREATE TABLE ledger (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      account_code TEXT NOT NULL,
      account_name TEXT NOT NULL,
      side TEXT NOT NULL,
      balance REAL NOT NULL DEFAULT 0,
      currency TEXT DEFAULT 'USD'
    );

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE trades (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      date TEXT NOT NULL,
      venue TEXT,
      symbol TEXT,
      side TEXT,
      quantity REAL,
      price REAL,
      pnl REAL,
      status TEXT
    );

CREATE TABLE transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  chain TEXT NOT NULL,
  asset TEXT,
  event TEXT NOT NULL,
  amount_usd REAL,
  direction TEXT,
  hash TEXT,
  url TEXT,
  source TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  memo TEXT, wallet_to TEXT, venue_id TEXT, trade_id TEXT
);

CREATE TABLE venues (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE wallets (
      address TEXT PRIMARY KEY,
      label TEXT,
      chain TEXT,
      monitored INTEGER DEFAULT 1,
      created_at TEXT DEFAULT (datetime('now'))
    , alias TEXT, emoji TEXT DEFAULT '💰', color TEXT DEFAULT '#3ddc97', notes TEXT);
