import type { MetadataRoute } from 'next';
import config from '@payload-config';
import { getPayload } from 'payload';
import { PUBLIC_ROUTES } from '@/server/routes';
import { TICKER_SYMBOLS } from '@/features/market/ticker/client';
import { COUNTRY_LIST, INDICATORS, CENTRAL_BANKS } from '@/features/economy/model';
import { MARKET_TYPES } from '@/features/trade/model';
import { INSTRUMENTS } from '@/features/trade/model';

// Published blog posts are read from the CMS, not a hand-kept list. The blog
// index and the post route are `force-dynamic` and read Payload, so the sitemap
// must read the SAME source or it drifts the moment a post is published — and it
// did: the weekly treasury digest (F12) is auto-published with a dated slug, so a
// hardcoded allowlist could never carry it. The old rule still holds, just from a
// live source: a slug in the sitemap is one the post route actually serves (that
// route queries PUBLISHED posts by slug), so the sitemap never advertises a dead
// URL. Regenerated hourly rather than per request — posts change rarely.
export const revalidate = 3600;

/** The published posts' slugs, straight from the CMS the blog pages read. */
async function publishedPosts(): Promise<{ slug: string; updatedAt?: string }[]> {
  const payload = await getPayload({ config });
  const { docs } = await payload.find({
    collection: 'posts',
    where: { status: { equals: 'published' } },
    sort: '-publishedAt',
    limit: 200,
    depth: 0,
  });
  return docs.map((p: any) => ({
    slug: String(p.slug),
    updatedAt: p.updatedAt ? String(p.updatedAt) : undefined,
  }));
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const staticRoutes = PUBLIC_ROUTES.map((route) => ({
    url: `https://fc.dwirijal.my.id${route.path === '/' ? '' : route.path}`,
    lastModified: new Date(),
    changeFrequency: route.path === '/' ? ('daily' as const) : ('hourly' as const),
    priority: route.priority,
  }));

  // Per-coin detail pages. These are a bounded, known set — the same explicit
  // allowlist the board itself quotes from — so they are enumerated here rather
  // than generated by crawling, which would let a stale or junk URL into the
  // sitemap. The coin changes on every sweep (spot, perp, future, option), so
  // hourly matches the price TTL.
  const tickerCoins = TICKER_SYMBOLS.map((symbol) => symbol.split('/')[0]);

  // Per-country economy profiles — same rule: enumerated from the economy
  // registry's own country table, never from a crawl. The profile's data moves
  // at most daily, so weekly is honest rather than hourly.
  const nationPages = COUNTRY_LIST.map((country) => ({
    url: `https://fc.dwirijal.my.id/economy/nation/${country.iso2.toLowerCase()}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.6,
  }));

  // Per-series pages and per-bank pages. Both are a bounded, known set — the
  // registry itself — so they are enumerated from it rather than generated by
  // crawling. A series that is not in the registry has no page (it 404s), so it
  // must not appear here.
  const indicatorPages = INDICATORS.map((ind) => ({
    url: `https://fc.dwirijal.my.id/economy/indicator/${ind.slug}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: ind.importance >= 3 ? 0.6 : 0.4,
  }));

  const centralBankPages = CENTRAL_BANKS.map((bank) => ({
    url: `https://fc.dwirijal.my.id/economy/central-bank/${bank.slug}`,
    lastModified: new Date(),
    changeFrequency: 'daily' as const,
    priority: 0.6,
  }));

  // Per-market-type trading boards. Same rule as the rest: a bounded, known set
  // — the trade taxonomy itself — enumerated from it, never crawled. A market
  // type that is not in the taxonomy has no page (the route 404s), so it must
  // not appear here. Prices move hourly, so hourly matches the ticker TTL.
  const tradeBoardPages = MARKET_TYPES.map((market) => ({
    url: `https://fc.dwirijal.my.id/trade/${market.id}`,
    lastModified: new Date(),
    changeFrequency: 'hourly' as const,
    priority: 0.6,
  }));

  // Per-instrument trading pages: the market-type boards crossed with the
  // instrument registry. A bounded, known set — enumerated from the two
  // allowlists rather than crawled. A market type the ticker cannot quote
  // (margin, `tickerType: null`) has no instrument page, so it is excluded;
  // including it would put a URL in the sitemap that the route 404s.
  const tradeInstrumentPages = MARKET_TYPES.filter((market) => market.tickerType !== null).flatMap((market) =>
    INSTRUMENTS.map((instrument) => ({
      url: `https://fc.dwirijal.my.id/trade/${market.id}/${instrument.id}`,
      lastModified: new Date(),
      changeFrequency: 'hourly' as const,
      priority: 0.5,
    })),
  );

  const blogPostPages = (await publishedPosts()).map((post) => ({
    url: `https://fc.dwirijal.my.id/blog/${post.slug}`,
    lastModified: post.updatedAt ? new Date(post.updatedAt) : new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  return [
    ...staticRoutes,
    ...blogPostPages,
    ...tickerCoins.map((coin) => ({
      url: `https://fc.dwirijal.my.id/market/crypto/${coin}`,
      lastModified: new Date(),
      changeFrequency: 'hourly' as const,
      priority: 0.6,
    })),
    ...nationPages,
    ...indicatorPages,
    ...centralBankPages,
    ...tradeBoardPages,
    ...tradeInstrumentPages,
  ];
}
