-- fudcourt-data domain schema — the tracked DDL for the data.* Postgres
-- schema (contract "Storage layout"; table inventory frozen in ADDENDUM B).
--
-- WHY A SEPARATE SCHEMA: the fudcourt read model (db/schema/pg-schema.sql,
-- `public`) is the treasury system of record that the sync replaces
-- wholesale (DR-040); the data sidecar writes live market/economic/DeFi
-- time series and must never share that blast radius. Everything here lives
-- in `data` and nothing in apps/web touches it. The apply precedent is the
-- executor's: db/schema/executor-schema.sql +
-- apps/executor/internal/repository.EnsureSchema, applied at STARTUP by the
-- Go runtime, one statement at a time (the extended query protocol refuses
-- multi-statement strings — see schema.go's splitter, which is
-- dollar-quote-aware because this file carries DO $$ blocks).
--
-- There is no separate migration runner. This file is the SOLE OWNER of the
-- DDL; db/schema/data-schema.sql is a byte-identical COPY of it (the
-- db/README ownership table lists both), and a repo-level Go test pins the
-- equality the same way the executor's TestEmbeddedSchemaMatchesTracked
-- does — byte-for-byte, which also guards comment-only edits.
--
-- Every statement is idempotent and re-appliable: CREATE ... IF NOT EXISTS
-- everywhere, named constraints (so a re-apply never stacks auto-named
-- duplicates), and the constraint guards duplicated in DO blocks exactly
-- like pg-schema.sql's canonical_reference block — CREATE TABLE IF NOT
-- EXISTS is a NO-OP when the table predates the constraint, so the DO block
-- is what makes a re-applied schema still enforce the invariant.
--
-- Conventions (ADDENDUM B, frozen):
--   * timestamps are timestamptz
--   * canonical ids are text and opaque (DR-036; never parsed, never
--     displayed as symbols)
--   * money/price/quantity are double precision (repo convention: wire
--     values are IEEE numbers upstream)
--   * identity PKs are bigint GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT,
--     not ALWAYS, so a writer may preserve an explicit id — same rule as
--     pg-schema.sql)
--   * hypertables (15 of them, listed in ADDENDUM B) are created with
--     create_hypertable(..., if_not_exists => TRUE) exactly like
--     pg-schema.sql; the partition column is part of every PK/unique index
--     (a Timescale requirement on hypertables)
--   * NO CREATE EXTENSION here: timescaledb is installed by pg-schema.sql
--     (trusted ext; QA 2026-10-09) and this file must apply cleanly to a
--     database that already has it; NO Timescale-License features
--     (no add_retention_policy, no continuous aggregates) — retention is
--     swept by the engine's Retention job (retention.go), not the database
--
-- TimescaleDB license note: create_hypertable itself is Apache-2-only.
CREATE SCHEMA IF NOT EXISTS data;

-- § Canonical entities (DR-036). Ids are MintID outputs; the natural keys
-- below are the uniqueness the minting rule already guarantees, restated at
-- the storage layer so a buggy writer cannot fork an entity.

-- 1. asset — symbol-addressable unit of value, keyed by kind + symbol.
CREATE TABLE IF NOT EXISTS data.asset (
  asset_id   text PRIMARY KEY,
  symbol     text NOT NULL,
  name       text,
  kind       text NOT NULL,
  chain_id   text,
  decimals   int,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 2. token — one contract deployment on one chain; address stored verbatim.
CREATE TABLE IF NOT EXISTS data.token (
  token_id     text PRIMARY KEY,
  chain_id     text NOT NULL,
  address      text NOT NULL,
  address_kind text,
  asset_id     text,
  symbol       text NOT NULL,
  name         text,
  decimals     int,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'token_chain_address_key') THEN
    ALTER TABLE data.token
      ADD CONSTRAINT token_chain_address_key UNIQUE (chain_id, address);
  END IF;
END
$$;

-- 3. chain — canonical chain keyed by lowercase name.
CREATE TABLE IF NOT EXISTS data.chain (
  chain_id         text PRIMARY KEY,
  name             text NOT NULL,
  display_name     text,
  kind             text NOT NULL,
  native_asset_id  text,
  chain_numeric_id int,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chain_name_key') THEN
    ALTER TABLE data.chain
      ADD CONSTRAINT chain_name_key UNIQUE (name);
  END IF;
END
$$;

-- 4. venue — one trading venue. known=false means "appears in the data but
-- this build cannot place an order there".
CREATE TABLE IF NOT EXISTS data.venue (
  venue_id     text PRIMARY KEY,
  name         text,
  kind         text NOT NULL,
  known        boolean NOT NULL DEFAULT false,
  market_types text[],
  url          text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- 5. instrument — one tradable market on one venue; natural_key is the
-- InstrumentKey spelling (minted from it).
CREATE TABLE IF NOT EXISTS data.instrument (
  instrument_id  text PRIMARY KEY,
  natural_key    text NOT NULL,
  venue_id       text NOT NULL,
  market_type    text NOT NULL,
  base_asset_id  text,
  quote_asset_id text,
  base_symbol    text NOT NULL,
  quote_symbol   text NOT NULL,
  expiry         timestamptz,
  strike         double precision,
  option_type    text,
  tick_size      double precision,
  lot_size       double precision,
  contract_size  double precision,
  isin           text,
  cusip          text,
  figi           text,
  ticker         text,
  status         text NOT NULL DEFAULT 'active',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'instrument_natural_key_key') THEN
    ALTER TABLE data.instrument
      ADD CONSTRAINT instrument_natural_key_key UNIQUE (natural_key);
  END IF;
END
$$;

-- 6. protocol — DeFi protocol keyed by slug.
CREATE TABLE IF NOT EXISTS data.protocol (
  protocol_id text PRIMARY KEY,
  slug        text NOT NULL,
  name        text,
  category    text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'protocol_slug_key') THEN
    ALTER TABLE data.protocol
      ADD CONSTRAINT protocol_slug_key UNIQUE (slug);
  END IF;
END
$$;

-- 7. country — ISO 3166-1 alpha-2.
CREATE TABLE IF NOT EXISTS data.country (
  country_id text PRIMARY KEY,
  iso2       text NOT NULL,
  name       text
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'country_iso2_key') THEN
    ALTER TABLE data.country
      ADD CONSTRAINT country_iso2_key UNIQUE (iso2);
  END IF;
END
$$;

-- 8. currency — ISO 4217.
CREATE TABLE IF NOT EXISTS data.currency (
  currency_id text PRIMARY KEY,
  code        text NOT NULL,
  name        text,
  kind        text
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'currency_code_key') THEN
    ALTER TABLE data.currency
      ADD CONSTRAINT currency_code_key UNIQUE (code);
  END IF;
END
$$;

-- 9. series — one economic/metric series: what it measures, about what
-- subject, from whom. subject_key default 'global' matches SeriesKey's
-- global-subject spelling.
CREATE TABLE IF NOT EXISTS data.series (
  series_id             text PRIMARY KEY,
  domain                text NOT NULL,
  metric                text NOT NULL,
  subject_key           text NOT NULL DEFAULT 'global',
  title                 text,
  unit                  text,
  frequency             text NOT NULL,
  country_id            text,
  asset_id              text,
  instrument_id         text,
  chain_id              text,
  protocol_id           text,
  venue_id              text,
  source                text NOT NULL,
  provider              text NOT NULL,
  provider_series_id    text NOT NULL,
  revision              text NOT NULL DEFAULT 'latest',
  is_derived            boolean NOT NULL DEFAULT false,
  schema_version        text NOT NULL,
  normalization_version text NOT NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'series_provider_provider_series_id_revision_key') THEN
    ALTER TABLE data.series
      ADD CONSTRAINT series_provider_provider_series_id_revision_key
      UNIQUE (provider, provider_series_id, revision);
  END IF;
END
$$;
CREATE INDEX IF NOT EXISTS series_domain_metric_idx ON data.series (domain, metric);
CREATE INDEX IF NOT EXISTS series_provider_idx ON data.series (provider);

-- 10. provider_symbol — the (provider, symbol) -> canonical id resolution
-- table. The CHECK mirrors pg-schema.sql's canonical_reference_kind_prefix:
-- kind must agree with the id's own namespace prefix, enforced at the
-- database so a wrong-namespace mapping is refused at write time. Named and
-- re-guarded in the DO block for the same re-apply reason as above.
CREATE TABLE IF NOT EXISTS data.provider_symbol (
  provider        text NOT NULL,
  provider_symbol text NOT NULL,
  kind            text NOT NULL,
  canonical_id    text NOT NULL,
  verified        boolean NOT NULL DEFAULT false,
  last_seen_at    timestamptz,
  PRIMARY KEY (provider, provider_symbol, kind),
  CONSTRAINT provider_symbol_canonical_id_kind CHECK (canonical_id LIKE kind || ':%')
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conrelid = 'data.provider_symbol'::regclass
                    AND conname  = 'provider_symbol_canonical_id_kind') THEN
    ALTER TABLE data.provider_symbol
      ADD CONSTRAINT provider_symbol_canonical_id_kind
      CHECK (canonical_id LIKE kind || ':%');
  END IF;
END
$$;
CREATE INDEX IF NOT EXISTS provider_symbol_canonical_id_idx ON data.provider_symbol (canonical_id);

-- 11. provider_source — one row per upstream data source.
CREATE TABLE IF NOT EXISTS data.provider_source (
  provider     text PRIMARY KEY,
  name         text,
  base_url     text,
  docs_url     text,
  requires_key boolean NOT NULL DEFAULT false,
  status       text NOT NULL DEFAULT 'active',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- § Job model + observability.

-- 12. job — the persisted registry row for one dataset job. The UNIQUE tuple
-- is the JobRef identity; cursor/last_*/status/retry_count are runtime state
-- the engine owns (EnsureJobs upserts schedule/priority/enabled and leaves
-- this state alone).
CREATE TABLE IF NOT EXISTS data.job (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider         text NOT NULL,
  dataset          text NOT NULL,
  subject          text NOT NULL DEFAULT '',
  mode             text NOT NULL DEFAULT 'poll',
  schedule_seconds int NOT NULL,
  priority         int NOT NULL DEFAULT 5,
  enabled          boolean NOT NULL DEFAULT true,
  cursor           jsonb,
  last_success     timestamptz,
  last_attempt     timestamptz,
  status           text NOT NULL DEFAULT 'idle',
  retry_count      int NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'job_provider_dataset_subject_mode_key') THEN
    ALTER TABLE data.job
      ADD CONSTRAINT job_provider_dataset_subject_mode_key
      UNIQUE (provider, dataset, subject, mode);
  END IF;
END
$$;
-- Scheduler's hot query: candidates are enabled jobs (DueJobs filters
-- last_attempt + schedule_seconds <= now, but enabled is the cheap pre-filter
-- the partial index serves).
CREATE INDEX IF NOT EXISTS job_enabled_status_idx ON data.job (status) WHERE enabled;

-- 13. ingestion_run — one row per attempt (the run journal).
CREATE TABLE IF NOT EXISTS data.ingestion_run (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider      text NOT NULL,
  dataset       text NOT NULL,
  subject       text NOT NULL DEFAULT '',
  mode          text NOT NULL,
  started_at    timestamptz NOT NULL,
  finished_at   timestamptz,
  status        text NOT NULL,
  rows_in       int,
  rows_written  int,
  rows_rejected int,
  error         text,
  attempt       int,
  job_id        bigint
);
CREATE INDEX IF NOT EXISTS ingestion_run_started_at_idx ON data.ingestion_run (started_at DESC);

-- 14. ingestion_error — the dead-letter table: terminal failures land here
-- with the offending payload (jsonb) for later replay; resolved flips the row
-- to acknowledged without deleting it.
CREATE TABLE IF NOT EXISTS data.ingestion_error (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider    text NOT NULL,
  dataset     text NOT NULL,
  subject     text NOT NULL DEFAULT '',
  occurred_at timestamptz NOT NULL,
  error       text NOT NULL,
  payload     jsonb,
  resolved    boolean NOT NULL DEFAULT false,
  run_id      bigint
);

-- § Market time series (hypertables). PKs include the partition column
-- (open_time/trade_time/at/...) as Timescale requires; upserts conflict on
-- the full PK.

-- 15. ohlcv — one OHLCV bar. PK (instrument, venue, timeframe, open_time) is
-- the upsert key; the secondary index serves venue-scoped reads.
CREATE TABLE IF NOT EXISTS data.ohlcv (
  instrument_id     text NOT NULL,
  venue_id          text NOT NULL,
  timeframe         text NOT NULL,
  open_time         timestamptz NOT NULL,
  close_time        timestamptz,
  o                 double precision NOT NULL,
  h                 double precision NOT NULL,
  l                 double precision NOT NULL,
  c                 double precision NOT NULL,
  volume_base       double precision,
  volume_quote      double precision,
  trade_count       bigint,
  vwap              double precision,
  source            text NOT NULL,
  retrieved_at      timestamptz,
  provider_record_id text,
  PRIMARY KEY (instrument_id, venue_id, timeframe, open_time)
);
SELECT create_hypertable('data.ohlcv', 'open_time', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS ohlcv_venue_instrument_timeframe_time_idx
  ON data.ohlcv (venue_id, instrument_id, timeframe, open_time DESC);

-- 16. trade — one executed trade; provider_trade_id is the venue's own id, so
-- the PK is the idempotency key for replays.
CREATE TABLE IF NOT EXISTS data.trade (
  instrument_id     text NOT NULL,
  venue_id          text NOT NULL,
  provider_trade_id text NOT NULL,
  trade_time        timestamptz NOT NULL,
  price             double precision NOT NULL,
  quantity          double precision NOT NULL,
  side              text,
  aggressor         text,
  source            text NOT NULL,
  retrieved_at      timestamptz,
  PRIMARY KEY (venue_id, instrument_id, provider_trade_id, trade_time)
);
SELECT create_hypertable('data.trade', 'trade_time', if_not_exists => TRUE);

-- 17. quote — one best bid/ask snapshot.
CREATE TABLE IF NOT EXISTS data.quote (
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  at            timestamptz NOT NULL,
  bid           double precision,
  ask           double precision,
  bid_size      double precision,
  ask_size      double precision,
  last          double precision,
  source        text NOT NULL,
  retrieved_at  timestamptz,
  PRIMARY KEY (instrument_id, venue_id, at)
);
SELECT create_hypertable('data.quote', 'at', if_not_exists => TRUE);

-- 18. orderbook — one depth snapshot; both sides stored as jsonb arrays of
-- [price, size] pairs.
CREATE TABLE IF NOT EXISTS data.orderbook (
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  at            timestamptz NOT NULL,
  depth         int,
  bids          jsonb,
  asks          jsonb,
  source        text NOT NULL,
  PRIMARY KEY (instrument_id, venue_id, at)
);
SELECT create_hypertable('data.orderbook', 'at', if_not_exists => TRUE);

-- 19. observation — one value of one series at one period under one revision.
-- period is the provider's own period label ('2026-09', '2026-10-09', ...);
-- observed_at carries the period as a timestamp for windowing.
CREATE TABLE IF NOT EXISTS data.observation (
  series_id          text NOT NULL,
  period             text NOT NULL DEFAULT '',
  observed_at        timestamptz NOT NULL,
  value              double precision,
  revision           text NOT NULL DEFAULT 'latest',
  vintage            timestamptz,
  source             text NOT NULL,
  provider           text NOT NULL,
  provider_record_id text,
  retrieved_at       timestamptz,
  PRIMARY KEY (series_id, period, observed_at, revision)
);
SELECT create_hypertable('data.observation', 'observed_at', if_not_exists => TRUE);

-- 20. funding — one funding settlement for one perpetual.
CREATE TABLE IF NOT EXISTS data.funding (
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  funding_time  timestamptz NOT NULL,
  rate          double precision NOT NULL,
  cap           double precision,
  predicted     boolean NOT NULL DEFAULT false,
  source        text NOT NULL,
  retrieved_at  timestamptz,
  PRIMARY KEY (instrument_id, venue_id, funding_time)
);
SELECT create_hypertable('data.funding', 'funding_time', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS funding_venue_time_idx ON data.funding (venue_id, funding_time DESC);

-- 21. open_interest — one open-interest snapshot.
CREATE TABLE IF NOT EXISTS data.open_interest (
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  at            timestamptz NOT NULL,
  oi_usd        double precision,
  oi_base       double precision,
  source        text NOT NULL,
  retrieved_at  timestamptz,
  PRIMARY KEY (instrument_id, venue_id, at)
);
SELECT create_hypertable('data.open_interest', 'at', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS open_interest_venue_at_idx ON data.open_interest (venue_id, at DESC);

-- 22. liquidation — one liquidation event. Identity PK + hypertable, so the
-- PK must include the partition column (Timescale requirement); rows are
-- append-only events, never upserted.
CREATE TABLE IF NOT EXISTS data.liquidation (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  at            timestamptz NOT NULL,
  side          text,
  price         double precision,
  quantity      double precision,
  value_usd     double precision,
  source        text NOT NULL,
  retrieved_at  timestamptz,
  PRIMARY KEY (id, at)
);
SELECT create_hypertable('data.liquidation', 'at', if_not_exists => TRUE);

-- 23. tvl_protocol — one TVL observation for one protocol on one chain
-- (chain_id '' = protocol-aggregated; DEFAULT '' matches ProtocolTVL's
-- zero value).
CREATE TABLE IF NOT EXISTS data.tvl_protocol (
  protocol_id  text NOT NULL,
  chain_id     text NOT NULL DEFAULT '',
  at           timestamptz NOT NULL,
  tvl_usd      double precision NOT NULL,
  source       text NOT NULL,
  retrieved_at timestamptz,
  PRIMARY KEY (protocol_id, chain_id, at)
);
SELECT create_hypertable('data.tvl_protocol', 'at', if_not_exists => TRUE);

-- 24. tvl_chain — one TVL observation for one chain.
CREATE TABLE IF NOT EXISTS data.tvl_chain (
  chain_id     text NOT NULL,
  at           timestamptz NOT NULL,
  tvl_usd      double precision NOT NULL,
  source       text NOT NULL,
  retrieved_at timestamptz,
  PRIMARY KEY (chain_id, at)
);
SELECT create_hypertable('data.tvl_chain', 'at', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS tvl_chain_at_idx ON data.tvl_chain (at DESC);

-- 25. pool — one DEX liquidity pool at one point in time. PK is the snapshot
-- key (pool, at); the UNIQUE tuple adds chain+address so a re-keyed pool id
-- cannot silently duplicate an (chain,address,at) snapshot.
CREATE TABLE IF NOT EXISTS data.pool (
  pool_id        text NOT NULL,
  at             timestamptz NOT NULL,
  chain_id       text NOT NULL,
  dex_venue_id   text,
  address        text NOT NULL,
  base_asset_id  text,
  quote_asset_id text,
  base_symbol    text,
  quote_symbol   text,
  fee_tier_bps   int,
  price          double precision,
  liquidity_usd  double precision,
  volume_24h_usd double precision,
  fdv_usd        double precision,
  source         text NOT NULL,
  retrieved_at   timestamptz,
  PRIMARY KEY (pool_id, at)
);
SELECT create_hypertable('data.pool', 'at', if_not_exists => TRUE);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pool_chain_address_at_key') THEN
    ALTER TABLE data.pool
      ADD CONSTRAINT pool_chain_address_at_key UNIQUE (chain_id, address, at);
  END IF;
END
$$;
CREATE INDEX IF NOT EXISTS pool_chain_liquidity_idx ON data.pool (chain_id, liquidity_usd DESC);

-- 26. news_article — one article from one provider.
CREATE TABLE IF NOT EXISTS data.news_article (
  article_id          text PRIMARY KEY,
  provider            text NOT NULL,
  provider_article_id text NOT NULL,
  headline            text NOT NULL,
  summary             text,
  url                 text NOT NULL,
  publisher           text,
  published_at        timestamptz,
  language            text,
  topics              text[],
  assets              text[],
  countries           text[],
  sentiment           double precision,
  importance          int,
  source              text,
  retrieved_at        timestamptz
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'news_article_provider_provider_article_id_key') THEN
    ALTER TABLE data.news_article
      ADD CONSTRAINT news_article_provider_provider_article_id_key
      UNIQUE (provider, provider_article_id);
  END IF;
END
$$;
CREATE INDEX IF NOT EXISTS news_article_published_at_idx ON data.news_article (published_at DESC);

-- 27. prediction_market — one market on a prediction platform.
CREATE TABLE IF NOT EXISTS data.prediction_market (
  market_id         text PRIMARY KEY,
  provider          text NOT NULL,
  provider_market_id text NOT NULL,
  question          text,
  outcomes          text[],
  prices            double precision[],
  liquidity_usd     double precision,
  volume_24h_usd    double precision,
  end_date          timestamptz,
  resolution_status text,
  source            text,
  retrieved_at      timestamptz
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'prediction_market_provider_provider_market_id_key') THEN
    ALTER TABLE data.prediction_market
      ADD CONSTRAINT prediction_market_provider_provider_market_id_key
      UNIQUE (provider, provider_market_id);
  END IF;
END
$$;

-- 28. supply — one token supply reading for one contract on one chain.
CREATE TABLE IF NOT EXISTS data.supply (
  chain_id           text NOT NULL,
  address            text NOT NULL,
  at                 timestamptz NOT NULL,
  asset_id           text,
  total_supply       double precision,
  circulating_supply double precision,
  source             text NOT NULL,
  retrieved_at       timestamptz,
  PRIMARY KEY (chain_id, address, at)
);
SELECT create_hypertable('data.supply', 'at', if_not_exists => TRUE);

-- 29. metric — derived datapoints of a series (the WriteMetric target); the
-- default source 'derived' matches MetricPoint's empty-Source spelling.
CREATE TABLE IF NOT EXISTS data.metric (
  series_id text NOT NULL,
  at        timestamptz NOT NULL,
  value     double precision,
  meta      jsonb,
  source    text NOT NULL DEFAULT 'derived',
  PRIMARY KEY (series_id, at)
);
SELECT create_hypertable('data.metric', 'at', if_not_exists => TRUE);

-- 30. option_quote — one options ticker snapshot for one option instrument.
CREATE TABLE IF NOT EXISTS data.option_quote (
  instrument_id text NOT NULL,
  venue_id      text NOT NULL,
  at            timestamptz NOT NULL,
  mark_price    double precision,
  index_price   double precision,
  bid           double precision,
  ask           double precision,
  volume_24h    double precision,
  open_interest double precision,
  iv            double precision,
  delta         double precision,
  gamma         double precision,
  theta         double precision,
  vega          double precision,
  source        text NOT NULL,
  retrieved_at  timestamptz,
  PRIMARY KEY (instrument_id, venue_id, at)
);
SELECT create_hypertable('data.option_quote', 'at', if_not_exists => TRUE);

-- 30b. liquidation natural identity: REST liquidation feeds re-deliver recent
-- events on every poll, so append-only rows need a deterministic dedup key.
CREATE UNIQUE INDEX IF NOT EXISTS liquidation_natural_key
  ON data.liquidation (venue_id, instrument_id, at, side, price, quantity);
