import type { MetadataRoute } from 'next';
import { PUBLIC_ROUTES } from '@/platform/routing/public-routes';
import { TICKER_SYMBOLS } from '@/features/ticker/client';
import { NATION_SLUGS } from '@/features/market/nation/client';

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = PUBLIC_ROUTES.map((route) => ({
    url: `https://fc.dwirijal.my.id${route.path === '/' ? '' : route.path}`,
    lastModified: new Date(),
    changeFrequency: route.path === '/' ? ('daily' as const) : ('hourly' as const),
    priority: route.priority,
  }));

  // Per-coin detail pages. These are a bounded, known set — the same explicit
  // allowlist the board itself quotes from — so they are enumerated here rather
  // than generated by crawling, which would let a stale or junk URL into the
  // sitemap. The coin changes on every sweep (spot, perp, future, option), so
  // hourly matches the price TTL.
  const tickerCoins = TICKER_SYMBOLS.map((symbol) => symbol.split('/')[0]);

  // Per-country economy profiles — same rule: enumerated from the nation
  // family's own country table, never from a crawl. The profile's annual data
  // moves at most daily, so weekly is honest rather than hourly.
  const nationPages = NATION_SLUGS.map((slug) => ({
    url: `https://fc.dwirijal.my.id/economy/nation/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'weekly' as const,
    priority: 0.6,
  }));

  return [
    ...staticRoutes,
    ...tickerCoins.map((coin) => ({
      url: `https://fc.dwirijal.my.id/market/ticker/${coin}`,
      lastModified: new Date(),
      changeFrequency: 'hourly' as const,
      priority: 0.6,
    })),
    ...nationPages,
  ];
}
