import type { MetadataRoute } from 'next';
import { PUBLIC_ROUTES } from '@/platform/routing/public-routes';
import { TICKER_SYMBOLS } from '@/features/ticker/client';

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = PUBLIC_ROUTES.map((route) => ({
    url: `https://fc.dwirijal.my.id${route.path === '/' ? '' : route.path}`,
    lastModified: new Date(),
    changeFrequency: route.path === '/' ? ('daily' as const) : ('hourly' as const),
    priority: route.priority,
  }));

  // Per-coin detail pages. These are a bounded, known set — the same explicit
  // allowlist the board itself quotes from — so they are enumerated here rather
  // than generated by crawling, which would let a stale or junk URL into the
  // sitemap. The coin changes on every sweep (spot, perp, future, option), so
  // hourly matches the price TTL.
  const tickerCoins = TICKER_SYMBOLS.map((symbol) => symbol.split('/')[0]);

  return [
    ...staticRoutes,
    ...tickerCoins.map((coin) => ({
      url: `https://fc.dwirijal.my.id/ticker/${coin}`,
      lastModified: new Date(),
      changeFrequency: 'hourly' as const,
      priority: 0.6,
    })),
  ];
}
