#!/usr/bin/env node
/**
 * gen-events.mjs — renders src/generated/events.ts from the canonical event
 * contract: shared/contracts/events/catalog.json (ids + aliases) and
 * shared/contracts/schemas/event-envelope.json (envelope shape).
 *
 * Single source: the catalog. This script is run by `bun run generate`.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(here, '..');
const contracts = path.join(pkgRoot, '..', '..', 'contracts');

const catalog = JSON.parse(readFileSync(path.join(contracts, 'events/catalog.json'), 'utf8'));
const envelope = JSON.parse(readFileSync(path.join(contracts, 'schemas/event-envelope.json'), 'utf8'));

const ids = catalog.events.map((e) => e.id);
const aliases = [...new Set(catalog.events.flatMap((e) => e.aliases ?? []))];
const union = (xs) => (xs.length > 0 ? xs.map((x) => `'${x}'`).join(' | ') : 'never');

/** Minimal JSON Schema → TS scalar mapping for the envelope fields. */
function tsType(schema) {
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  const nullable = types.includes('null');
  const base = types.filter((t) => t !== 'null')[0];
  let ts;
  if (base === 'string') ts = 'string';
  else if (base === 'number' || base === 'integer') ts = 'number';
  else if (base === 'boolean') ts = 'boolean';
  else if (base === 'object') ts = 'Record<string, unknown>';
  else if (base === 'array') ts = `${tsType(schema.items ?? {})}[]`;
  else ts = 'unknown';
  return nullable ? `${ts} | null` : ts;
}

const envelopeFields = Object.entries(envelope.properties).map(([name, schema]) => {
  const optional = (envelope.required ?? []).includes(name) ? '' : '?';
  const type = name === 'event_type' ? 'EventType | LegacyEventName' : tsType(schema);
  return `  ${name}${optional}: ${type};`;
});

const out = `// AUTO-GENERATED by scripts/gen-events.mjs from
//   shared/contracts/events/catalog.json        (event_type ids + aliases)
//   shared/contracts/schemas/event-envelope.json (envelope shape)
// Do not edit by hand — run \`bun run generate\`.

/** Stable canonical event_type id (PascalCase). */
export type EventType =
  | ${union(ids).split(' | ').join('\n  | ')};

/** Legacy TS ExecutionEventName spellings — accepted aliases of the same ids. */
export type LegacyEventName =
  | ${union(aliases).split(' | ').join('\n  | ')};

/** event_version is a semver-ish integer; additive evolution keeps it. */
export type EventVersion = (typeof catalog)['event_version'];

/** The canonical event envelope (mirrors schemas/event-envelope.json). */
export interface EventEnvelope {
${envelopeFields.join('\n')}
}

/** One catalog entry: stable id, its accepted aliases, observed payload keys. */
export interface CatalogEventEntry {
  id: EventType;
  event_version: number;
  aliases: readonly LegacyEventName[];
  objective_names: readonly string[];
  observed?: readonly string[];
  description: string;
}

/** The event catalog as data (single source: shared/contracts/events/catalog.json). */
export const catalog = ${JSON.stringify(catalog, null, 2)} as const;

/** Catalog entries, in catalog order. */
export const events: readonly CatalogEventEntry[] = catalog.events;
`;

mkdirSync(path.join(pkgRoot, 'src/generated'), { recursive: true });
writeFileSync(path.join(pkgRoot, 'src/generated/events.ts'), out);
console.log(`gen-events: wrote src/generated/events.ts (${ids.length} event types, ${aliases.length} aliases)`);
