-- Local read model for fudcourt (DR-019).
--
-- Turso stays the system of record: the Rust reconciler, scripts/tools/sync-live.py
-- and the app's POST endpoints all write libsql. This database is the READ side,
-- kept in parity by scripts/tools/pg-load.ts (Turso -> Postgres, idempotent upsert)
-- on a 60 s timer and after every local write.
--
-- It exists for one measured reason: a Turso round trip from the homeserver is
-- ~394 ms, a local Postgres round trip is 2.8 ms. Reads are on the fast path.
--
-- Types map 1:1 from database/schema/schema.sql so the JSON the routes emit is byte-identical:
--   TEXT        -> text        (including the datetime('now') columns, kept as
--                                the same 'YYYY-MM-DD HH:MM:SS' UTC string, so
--                                the board renders the old value, not a Date)
--   REAL        -> double precision
--   INTEGER PK  -> integer ... GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT,
--                  not ALWAYS, so pg-load can preserve the source ids)
-- Hand-written, unlike database/schema/schema.sql: Postgres DDL cannot be dumped from SQLite.

CREATE TABLE IF NOT EXISTS accounts (
  code      text PRIMARY KEY,
  name      text NOT NULL,
  type      text NOT NULL,
  statement text NOT NULL
);

CREATE TABLE IF NOT EXISTS assets (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain      text NOT NULL,
  asset      text NOT NULL,
  quantity   double precision,
  value_usd  double precision,
  share_pct  double precision,
  wallet     text,
  updated_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS journal (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date           text NOT NULL,
  entry_code     text NOT NULL,
  debit_account  text,
  credit_account text,
  memo           text,
  amount         double precision,
  status         text DEFAULT 'Posted',
  created_at     text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ledger (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code text NOT NULL,
  account_name text NOT NULL,
  side         text NOT NULL,
  balance      double precision NOT NULL DEFAULT 0,
  currency     text DEFAULT 'USD'
);

CREATE TABLE IF NOT EXISTS trades (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date     text NOT NULL,
  venue    text,
  symbol   text,
  side     text,
  quantity double precision,
  price    double precision,
  pnl      double precision,
  status   text
);

CREATE TABLE IF NOT EXISTS transactions (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date       text NOT NULL,
  chain      text NOT NULL,
  asset      text,
  event      text NOT NULL,
  amount_usd double precision,
  direction  text,
  hash       text,
  url        text,
  source     text,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  memo       text,
  wallet_to  text,
  venue_id   text,
  trade_id   text
);

CREATE TABLE IF NOT EXISTS venues (
  id   text PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
  address    text PRIMARY KEY,
  label      text,
  chain      text,
  monitored  integer DEFAULT 1,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  alias      text,
  emoji      text DEFAULT '💰',
  color      text DEFAULT '#3ddc97',
  notes      text
);

-- TimescaleDB: the one thing Turso never gave us. Every asset snapshot sync-live.py
-- appends (it INSERTs into `assets` each run rather than upserting) becomes a
-- time-series row here, so "what was I worth at time T" stops being a table scan
-- of the live table and becomes a hypertable lookup. `assets` above stays the
-- latest-state table the board reads.
CREATE TABLE IF NOT EXISTS asset_history (
  ts        timestamptz NOT NULL,
  chain     text NOT NULL,
  asset     text NOT NULL,
  wallet    text,
  quantity  double precision,
  value_usd double precision,
  share_pct double precision
);

SELECT create_hypertable('asset_history', 'ts', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS asset_history_asset_ts ON asset_history (asset, ts DESC);
-- The loader upserts on this key. `wallet` is nullable in the source, and two
-- NULLs never conflict in Postgres, so the index coalesces it: without that,
-- every re-run would append a duplicate row for a wallet-less asset.
CREATE UNIQUE INDEX IF NOT EXISTS asset_history_snapshot
  ON asset_history (ts, chain, asset, (coalesce(wallet, '')));

-- And the same for the market side: a compact price series the boards can chart
-- without re-hitting a provider for history. Written by the price sampler.
CREATE TABLE IF NOT EXISTS price_history (
  ts     timestamptz NOT NULL,
  symbol text NOT NULL,
  source text NOT NULL,
  price  double precision NOT NULL
);

SELECT create_hypertable('price_history', 'ts', if_not_exists => TRUE);
CREATE UNIQUE INDEX IF NOT EXISTS price_history_symbol_ts_source
  ON price_history (symbol, ts, source);

-- Retention: 90 days, beyond which the boards never look. It is a plain DELETE in
-- scripts/tools/pg-load.ts rather than add_retention_policy(), because the
-- retention-policy API is Timescale License, not Apache-2 (this build refuses it:
-- "not supported under the current 'apache' license"). A DELETE of <= a few
-- thousand rows per day needs no policy engine, and keeping the install
-- Apache-only keeps the licence story as simple as the rest of the stack.
