-- fudcourt's system of record (DR-040).
--
-- Postgres+TimescaleDB is the SINGLE system of record. Every writer — the Python
-- sync (tests/oracle/sync-live.py), the Rust crate (backend/sync) and the web
-- (frontend/web/src/platform/db/client.ts) — reads and writes HERE. There is no
-- remote mirror and no second store; the DR-019 Turso/libSQL split is retired.
--
-- Types: TEXT -> text (the datetime columns stay 'YYYY-MM-DD HH:MM:SS' UTC
-- strings, so the boards render the stored value rather than a re-formatted
-- Date), REAL -> double precision, INTEGER PK -> integer GENERATED BY DEFAULT AS
-- IDENTITY (BY DEFAULT, not ALWAYS, so a writer may preserve an explicit id).

CREATE TABLE IF NOT EXISTS accounts (
  code      text PRIMARY KEY,
  name      text NOT NULL,
  type      text NOT NULL,
  statement text NOT NULL
);

CREATE TABLE IF NOT EXISTS assets (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain      text NOT NULL,
  asset      text NOT NULL,
  quantity   double precision,
  value_usd  double precision,
  share_pct  double precision,
  wallet     text,
  updated_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS journal (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date           text NOT NULL,
  entry_code     text NOT NULL,
  debit_account  text,
  credit_account text,
  memo           text,
  amount         double precision,
  status         text DEFAULT 'Posted',
  created_at     text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS ledger (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_code text NOT NULL,
  account_name text NOT NULL,
  side         text NOT NULL,
  balance      double precision NOT NULL DEFAULT 0,
  currency     text DEFAULT 'USD'
);

CREATE TABLE IF NOT EXISTS trades (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date     text NOT NULL,
  venue    text,
  symbol   text,
  side     text,
  quantity double precision,
  price    double precision,
  pnl      double precision,
  status   text
);

CREATE TABLE IF NOT EXISTS transactions (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date       text NOT NULL,
  chain      text NOT NULL,
  asset      text,
  event      text NOT NULL,
  amount_usd double precision,
  direction  text,
  hash       text,
  url        text,
  source     text,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  memo       text,
  wallet_to  text,
  venue_id   text,
  trade_id   text
);

CREATE TABLE IF NOT EXISTS venues (
  id   text PRIMARY KEY,
  name text NOT NULL,
  type text NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
  address    text PRIMARY KEY,
  label      text,
  chain      text,
  monitored  integer DEFAULT 1,
  created_at text DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  alias      text,
  emoji      text DEFAULT '💰',
  color      text DEFAULT '#3ddc97',
  notes      text
);

-- TimescaleDB time series. Every `assets` observation — inserted by the sync, a
-- route or an operator — is appended here by the `assets_snapshot` trigger below,
-- so "what was I worth at time T" stops being a table scan of the live table and
-- becomes a hypertable lookup. `assets` above stays the latest-state table the
-- board reads.
CREATE TABLE IF NOT EXISTS asset_history (
  ts        timestamptz NOT NULL,
  chain     text NOT NULL,
  asset     text NOT NULL,
  wallet    text,
  quantity  double precision,
  value_usd double precision,
  share_pct double precision
);

SELECT create_hypertable('asset_history', 'ts', if_not_exists => TRUE);
CREATE INDEX IF NOT EXISTS asset_history_asset_ts ON asset_history (asset, ts DESC);
-- The loader upserts on this key. `wallet` is nullable in the source, and two
-- NULLs never conflict in Postgres, so the index coalesces it: without that,
-- every re-run would append a duplicate row for a wallet-less asset.
CREATE UNIQUE INDEX IF NOT EXISTS asset_history_snapshot
  ON asset_history (ts, chain, asset, (coalesce(wallet, '')));

-- The snapshot is a TRIGGER, not application code (DR-040): the writer only has
-- to INSERT into `assets` and the time series takes care of itself, so the Python
-- sync, the Rust crate and a manual `psql` insert all snapshot identically. The
-- sync replaces `assets` wholesale (DELETE then INSERT) and a row trigger fires
-- per inserted row, so that is exactly one snapshot per observation. The ts is the
-- observation's own `updated_at` (a UTC wall-clock string), parsed as UTC; the
-- ON CONFLICT matches asset_history_snapshot so a re-insert at the same ts updates
-- in place rather than duplicating.
CREATE OR REPLACE FUNCTION assets_snapshot() RETURNS trigger AS $$
BEGIN
  INSERT INTO asset_history (ts, chain, asset, wallet, quantity, value_usd, share_pct)
  VALUES (COALESCE(NULLIF(NEW.updated_at, '')::timestamp AT TIME ZONE 'UTC', now()),
          NEW.chain, NEW.asset, NEW.wallet, NEW.quantity, NEW.value_usd, NEW.share_pct)
  ON CONFLICT (ts, chain, asset, (coalesce(wallet, ''))) DO UPDATE
    SET quantity  = EXCLUDED.quantity,
        value_usd = EXCLUDED.value_usd,
        share_pct = EXCLUDED.share_pct;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS assets_snapshot_trg ON assets;
CREATE TRIGGER assets_snapshot_trg AFTER INSERT ON assets
  FOR EACH ROW EXECUTE FUNCTION assets_snapshot();

-- And the same for the market side: a compact price series the boards can chart
-- without re-hitting a provider for history. Written by the price sampler.
CREATE TABLE IF NOT EXISTS price_history (
  ts     timestamptz NOT NULL,
  symbol text NOT NULL,
  source text NOT NULL,
  price  double precision NOT NULL
);

SELECT create_hypertable('price_history', 'ts', if_not_exists => TRUE);
CREATE UNIQUE INDEX IF NOT EXISTS price_history_symbol_ts_source
  ON price_history (symbol, ts, source);

-- Retention: 90 days, beyond which the boards never look. It is a plain DELETE in
-- tests/oracle/sync-live.py (after the sync writes) rather than
-- add_retention_policy(), because the retention-policy API is Timescale License,
-- not Apache-2 (this build refuses it: "not supported under the current 'apache'
-- license"). A DELETE of <= a few thousand rows per day needs no policy engine,
-- and keeping the install Apache-only keeps the licence story as simple as the
-- rest of the stack.
--
-- Durable canonical identity (DR-036). The canonical id space lives code-side in
-- backend/api/internal/markets/reference (minted, opaque) and ships as the artifact
-- shared/contracts/data/reference.json. This is its SQL half: the published
-- (provider, provider_id) -> canonical_id resolution table, so a database consumer
-- can resolve through a canonical id instead of a symbol. It is ADDITIVE and
-- UNWIRED: nothing reads it yet (no FK, no column on any money-bearing row, no
-- runtime caller), and the loader that fills it is
-- backend/api/internal/markets/reference/loader.go. The table is a derived CACHE of
-- the artifact, not a second source: the loader UPSERTs the artifact's rows and
-- prunes any provider key it no longer sees, so the artifact stays the single source
-- of truth (no id is re-derived here).
--
-- Types follow the artifact where a column has a source: text for every id and key
-- (ids are opaque strings, never parsed), text for `loaded_at` for the same reason as
-- the datetime columns above (a dump round-trips as the same 'YYYY-MM-DD HH:MM:SS'
-- string rather than re-rendering through a Date), and boolean for the miss table's
-- `known_absence`. No money is stored here: every column is an identifier, a
-- namespace label, a timestamp string, or the miss table's prose.
CREATE TABLE IF NOT EXISTS canonical_reference (
  provider     text NOT NULL,
  provider_id  text NOT NULL,
  canonical_id text NOT NULL,
  kind         text NOT NULL,
  loaded_at    text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (provider, provider_id),
  -- `kind` must agree with the id's own prefix, so an id stored under the wrong
  -- namespace is refused at write time instead of producing a wrong join. That makes
  -- `kind` redundant-but-ENFORCED rather than merely advisory: the prefix is a string,
  -- and this CHECK is the database-level form of the same invariant (the loader's
  -- validateDocument checks it too, but the table must not rely on its writer for its
  -- own integrity). `LIKE kind || ':%'` is valid because the pattern is a plain
  -- concatenation — no LIKE metacharacters appear in a kind.
  --
  -- The constraint is NAMED and duplicated in the guarded DO block below. That is
  -- not belt-and-braces for its own sake: `CREATE TABLE IF NOT EXISTS` is a NO-OP
  -- when the table already exists, so an inline CHECK only ever lands at FIRST
  -- creation. This file is designed to be re-appliable (every statement is
  -- IF NOT EXISTS), and a plain-psql applier whose table predates this DDL would
  -- otherwise run the whole file to completion WITHOUT the invariant — silently.
  -- The DO block re-adds the constraint (only when absent, matched by name) so a
  -- re-applied schema still refuses a bad `kind`. The name is what makes it
  -- idempotent: without it `ALTER TABLE ... ADD CONSTRAINT` is a second,
  -- auto-named constraint and every re-apply adds another.
  CONSTRAINT canonical_reference_kind_prefix CHECK (canonical_id LIKE kind || ':%')
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
                  WHERE conrelid = 'canonical_reference'::regclass
                    AND conname  = 'canonical_reference_kind_prefix') THEN
    ALTER TABLE canonical_reference
      ADD CONSTRAINT canonical_reference_kind_prefix
      CHECK (canonical_id LIKE kind || ':%');
  END IF;
END
$$;
-- `kind` is the canonical_id's namespace. The values the loader writes today are
-- exactly the EntityKinds the reference registry mints ('asset' | 'chain' | 'token'
-- | 'venue') because it derives its accepted set from `EntityKinds`. The DDL
-- deliberately does NOT pin that closed set a second time: the CHECK above enforces
-- the structural invariant (kind agrees with the id's prefix), while "which
-- namespaces exist" stays owned by the registry, so adding one does not become a
-- DDL migration. 'instrument' is therefore not rejected by the table — it simply
-- cannot arrive, because instruments are minted
-- (`backend/api/internal/markets/instruments/canonical.go`) but are absent from
-- `reference.json`, and the loader refuses any namespace outside `EntityKinds`.
CREATE INDEX IF NOT EXISTS canonical_reference_canonical_id
  ON canonical_reference (canonical_id);
CREATE INDEX IF NOT EXISTS canonical_reference_kind
  ON canonical_reference (kind);
-- Known-but-unresolved provider identifiers (the artifact's `misses`), stored as
-- their own rows so a consumer's left join sees a NULL target instead of assuming
-- the key is absent from upstream. `known_absence` marks one the tree itself
-- stores lossily (the `SPL:<mint6>` truncation) versus one simply not registered.
CREATE TABLE IF NOT EXISTS canonical_reference_miss (
  provider      text NOT NULL,
  provider_id   text NOT NULL,
  kind          text NOT NULL,
  reason        text NOT NULL,
  reported_as   text NOT NULL DEFAULT '',
  known_absence boolean NOT NULL DEFAULT false,
  loaded_at     text NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  PRIMARY KEY (provider, provider_id)
);
